os: osx
language: node_js
node_js:
  - '10'

script:
  - brew tap mesca/luarocks
  - brew install luarocks51 --with-luajit
  - luarocks-jit install busted --local
  - eval $(luarocks-jit path --bin)
  - npm test
  - npm run build

deploy:
  provider: npm
  email: evan@moonside.games
  api_key:
    secure: EK/nCcvaAclWhnlvUxM3JkqMfnTZaEiR+pX+wirQvFAnbfJoJKeRcZ63QrdsqfKd0vSuWObDGnC+NdqgHxFcKkY1QJopR/Ty06atYrSx+DREFshd5iwieuyIcuJ2Xz6ReAKu3umhqDNMHiZiI2X4cKUcbMQZE0CbvP63HSgwQ4Wh/a3zM7e9r6ZnL4W4lve89kl5aac/AXFNT2PHN+GSX0KN8qUoiStyFNJEABOortUUovSoV0MSTLZ6+hK4p1O7Wqe1F1gEZvNry862kMh87Yp2n+lVhtm28FY2D1eS03VMJ8TSTC9Rm+2a2CMFcMM5wuGX8zXLj0mqeY58+hsiEjUEzg33fqYmtGPW1QWXztDHZzAOIhv7nsPmW7eMp+fwxgjj9jkxnqvKAvUab4zFAknYXiJfte+vnYhMvyqGfkopzUFSO/0XtBHGUlN1ODnwmSlyvpD0hb1AbgI4/dKmXt57CUnEkJVq2m2Gsf8IT612gA33QiCQaLee4Np5gLIntVirEe6aiH2m5ZYioMgEdu46TZaBK/wkOC44pyXZH25/V9au8evqZG4ZN32Jf9cv5u8SLPpd8le6pqWBOwjts+y7+wNJc2gw6Rpq9B+Vm8bxD1hEF6W01K3BLtbYZc6x+2IZGPLB+durvVEeWdH+MGKlc4vEzosuKO/Ay4QjIMI=
  on:
    tags: true
    repo: encompass-ecs/encompass-gc-optimized-collections
  skip_cleanup: true
